package erpsolgls.erpsolglsmodel.erpsolglsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 17 22:38:48 PKT 2022
// ---------------------------------------------------------------------
public interface VoucherView extends ViewObject {
    void doSuperviseGLVoucher();
}

