package erpsolgls.erpsolglsmodel.erpsolglsqvo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import erpsolgls.erpsolglsmodel.erpsolglsqvo.common.VwGeneralLedgerReportQVO;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 20 14:55:34 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwGeneralLedgerReportQVOImpl extends ViewObjectImpl implements VwGeneralLedgerReportQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public VwGeneralLedgerReportQVOImpl() {
    }
    
    
    public void doSetERPSolGLReportDefault() {
        ViewObject vo=getApplicationModule().findViewObject("QvoGLLoc");
        if (vo!=null) {
            vo.remove();
       }
        vo=getApplicationModule().createViewObjectFromQueryStmt("QvoGLLoc", "select locationid, location_description from all_locations where locationid='"+ERPSolGlobClassModel.doGetUserLocationCode()+"'");
        vo.executeQuery();;
        this.first().setAttribute("txtLocationId", vo.first().getAttribute(0));
        this.first().setAttribute("txtLocationName", vo.first().getAttribute(1));
        System.out.println(ERPSolGlobClassModel.doGetUserCompanyCode() +" comp code");
        this.first().setAttribute("txtCompanyCode", ERPSolGlobClassModel.doGetUserCompanyCode());
    //        this.first().setAttribute("txtFromDate", this.first().getAttribute("txtDefaultDate"));
    //        this.first().setAttribute("txtToDate", this.first().getAttribute("txtDefaultDate"));
        vo.remove();
    }
}

