package erpsolgls.erpsolglsmodel.erpsolglseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 03 11:24:10 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ChartOfAccImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GlnatureOfAC,
        GlbroadCategory,
        GlcontrolAC,
        GlsubControlAC,
        GlsubsidaryAC,
        Description,
        OldGlCode,
        CostType,
        Remarks1,
        Remarks2,
        RestrictGlCode,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        CoaType,
        VoucherDet;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GLNATUREOFAC = AttributesEnum.GlnatureOfAC.index();
    public static final int GLBROADCATEGORY = AttributesEnum.GlbroadCategory.index();
    public static final int GLCONTROLAC = AttributesEnum.GlcontrolAC.index();
    public static final int GLSUBCONTROLAC = AttributesEnum.GlsubControlAC.index();
    public static final int GLSUBSIDARYAC = AttributesEnum.GlsubsidaryAC.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int OLDGLCODE = AttributesEnum.OldGlCode.index();
    public static final int COSTTYPE = AttributesEnum.CostType.index();
    public static final int REMARKS1 = AttributesEnum.Remarks1.index();
    public static final int REMARKS2 = AttributesEnum.Remarks2.index();
    public static final int RESTRICTGLCODE = AttributesEnum.RestrictGlCode.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int COATYPE = AttributesEnum.CoaType.index();
    public static final int VOUCHERDET = AttributesEnum.VoucherDet.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ChartOfAccImpl() {
    }

    /**
     * Gets the attribute value for GlnatureOfAC, using the alias name GlnatureOfAC.
     * @return the value of GlnatureOfAC
     */
    public String getGlnatureOfAC() {
        return (String) getAttributeInternal(GLNATUREOFAC);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlnatureOfAC.
     * @param value value to set the GlnatureOfAC
     */
    public void setGlnatureOfAC(String value) {
        setAttributeInternal(GLNATUREOFAC, value);
    }

    /**
     * Gets the attribute value for GlbroadCategory, using the alias name GlbroadCategory.
     * @return the value of GlbroadCategory
     */
    public String getGlbroadCategory() {
        return (String) getAttributeInternal(GLBROADCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlbroadCategory.
     * @param value value to set the GlbroadCategory
     */
    public void setGlbroadCategory(String value) {
        setAttributeInternal(GLBROADCATEGORY, value);
    }

    /**
     * Gets the attribute value for GlcontrolAC, using the alias name GlcontrolAC.
     * @return the value of GlcontrolAC
     */
    public String getGlcontrolAC() {
        return (String) getAttributeInternal(GLCONTROLAC);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlcontrolAC.
     * @param value value to set the GlcontrolAC
     */
    public void setGlcontrolAC(String value) {
        setAttributeInternal(GLCONTROLAC, value);
    }

    /**
     * Gets the attribute value for GlsubControlAC, using the alias name GlsubControlAC.
     * @return the value of GlsubControlAC
     */
    public String getGlsubControlAC() {
        return (String) getAttributeInternal(GLSUBCONTROLAC);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlsubControlAC.
     * @param value value to set the GlsubControlAC
     */
    public void setGlsubControlAC(String value) {
        setAttributeInternal(GLSUBCONTROLAC, value);
    }

    /**
     * Gets the attribute value for GlsubsidaryAC, using the alias name GlsubsidaryAC.
     * @return the value of GlsubsidaryAC
     */
    public String getGlsubsidaryAC() {
        return (String) getAttributeInternal(GLSUBSIDARYAC);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlsubsidaryAC.
     * @param value value to set the GlsubsidaryAC
     */
    public void setGlsubsidaryAC(String value) {
        setAttributeInternal(GLSUBSIDARYAC, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OldGlCode, using the alias name OldGlCode.
     * @return the value of OldGlCode
     */
    public String getOldGlCode() {
        return (String) getAttributeInternal(OLDGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OldGlCode.
     * @param value value to set the OldGlCode
     */
    public void setOldGlCode(String value) {
        setAttributeInternal(OLDGLCODE, value);
    }

    /**
     * Gets the attribute value for CostType, using the alias name CostType.
     * @return the value of CostType
     */
    public String getCostType() {
        return (String) getAttributeInternal(COSTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostType.
     * @param value value to set the CostType
     */
    public void setCostType(String value) {
        setAttributeInternal(COSTTYPE, value);
    }

    /**
     * Gets the attribute value for Remarks1, using the alias name Remarks1.
     * @return the value of Remarks1
     */
    public String getRemarks1() {
        return (String) getAttributeInternal(REMARKS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks1.
     * @param value value to set the Remarks1
     */
    public void setRemarks1(String value) {
        setAttributeInternal(REMARKS1, value);
    }

    /**
     * Gets the attribute value for Remarks2, using the alias name Remarks2.
     * @return the value of Remarks2
     */
    public String getRemarks2() {
        return (String) getAttributeInternal(REMARKS2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks2.
     * @param value value to set the Remarks2
     */
    public void setRemarks2(String value) {
        setAttributeInternal(REMARKS2, value);
    }

    /**
     * Gets the attribute value for RestrictGlCode, using the alias name RestrictGlCode.
     * @return the value of RestrictGlCode
     */
    public String getRestrictGlCode() {
        return (String) getAttributeInternal(RESTRICTGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RestrictGlCode.
     * @param value value to set the RestrictGlCode
     */
    public void setRestrictGlCode(String value) {
        setAttributeInternal(RESTRICTGLCODE, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for CoaType, using the alias name CoaType.
     * @return the value of CoaType
     */
    public String getCoaType() {
        return (String) getAttributeInternal(COATYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaType.
     * @param value value to set the CoaType
     */
    public void setCoaType(String value) {
        setAttributeInternal(COATYPE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getVoucherDet() {
        return (RowIterator) getAttributeInternal(VOUCHERDET);
    }

    /**
     * @param glnatureOfAC key constituent
     * @param glbroadCategory key constituent
     * @param glcontrolAC key constituent
     * @param glsubControlAC key constituent
     * @param glsubsidaryAC key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String glnatureOfAC, String glbroadCategory, String glcontrolAC,
                                       String glsubControlAC, String glsubsidaryAC) {
        return new Key(new Object[] { glnatureOfAC, glbroadCategory, glcontrolAC, glsubControlAC, glsubsidaryAC });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolgls.erpsolglsmodel.erpsolglseo.ChartOfAcc");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPISGenertePK("NO");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

