package erpsolgls.erpsolglsmodel.erpsolglsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 20 15:00:25 PKT 2022
// ---------------------------------------------------------------------
public interface VwGeneralLedgerReportQVO extends ViewObject {
    void doSetERPSolGLReportDefault();

    void doSetERPSolGLDocumentUnsubmit();
}

